CREATE DATABASE testDB;

USE testDB;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE pedidos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    pepperoni INT DEFAULT 0,
    rucula INT DEFAULT 0,
    chocolate INT DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(id)
);